{
    "groupName": "SP500",
    "count": 12,
    "rankProperty": "CHANGE_PCT",
    "rankOrder": "BOTH",
    "filterProperty": "LAST_PRICE",
    "filterOperator": "GREATER",
    "filterValue": "1",
    "cacheServedQuotes": false,
    "rankingTime": 28,
    "delayed": false,
    "source": "SAVED",
    "rankDateTime": "Mon Apr 01 18:33:02 EDT 2024",
    "indexImpact": false,
    "rankedSymbolList": [
        {
            "rankOrder": "TOP",
            "rankedSymbols": [
                {
                    "issueId": 202757,
                    "cnbcSymbol": "MMM",
                    "vendorSymbol": "MMM",
                    "symbolDesc": "3M Co",
                    "shares": null,
                    "cached": false,
                    "symbolData": {
                        "lastPrice": 94.02,
                        "change": 5.3375,
                        "changePct": 6.0187,
                        "changeAfter": -0.08,
                        "changePre": 2.5675,
                        "changePctAfter": -0.0851,
                        "changePctPre": 2.8952,
                        "prevClosePrice": 88.6825,
                        "volume": 12996002,
                        "yearhHighInd": 0,
                        "yearhLowInd": 0,
                        "impliedVolatality": 0.2561,
                        "pctTenDayVol": 1.7051,
                        "peRatio": 0.0,
                        "yield": 6.8108,
                        "tradingStatus": 1,
                        "lastTime": "22:33:00.000",
                        "vendor": "RBDS"
                    },
                    "defaultVendor": "RBDS",
                    "delayed": false,
                    "vendorKeys": [
                        "RBDS",
                        "ARCA",
                        "NLS"
                    ]
                },
                {
                    "issueId": 207106,
                    "cnbcSymbol": "MU",
                    "vendorSymbol": "MU.O",
                    "symbolDesc": "Micron Technology Inc",
                    "shares": null,
                    "cached": false,
                    "symbolData": {
                        "lastPrice": 124.3,
                        "change": 6.41,
                        "changePct": 5.4373,
                        "changeAfter": 1.14,
                        "changePre": 1.39,
                        "changePctAfter": 0.9171,
                        "changePctPre": 1.1791,
                        "prevClosePrice": 117.89,
                        "volume": 44231548,
                        "yearhHighInd": 1,
                        "yearhLowInd": 0,
                        "impliedVolatality": 0.3724,
                        "pctTenDayVol": 1.1317,
                        "peRatio": 0.0,
                        "yield": 0.3902,
                        "tradingStatus": 1,
                        "lastTime": "22:32:50.000",
                        "vendor": "RBDS"
                    },
                    "defaultVendor": "RBDS",
                    "delayed": false,
                    "vendorKeys": [
                        "RBDS",
                        "ARCA",
                        "NLS"
                    ]
                },
                {
                    "issueId": 288727,
                    "cnbcSymbol": "WYNN",
                    "vendorSymbol": "WYNN.O",
                    "symbolDesc": "Wynn Resorts Ltd",
                    "shares": null,
                    "cached": false,
                    "symbolData": {
                        "lastPrice": 106.56,
                        "change": 4.33,
                        "changePct": 4.2355,
                        "changeAfter": -0.1,
                        "changePre": 0.74,
                        "changePctAfter": -0.0938,
                        "changePctPre": 0.7239,
                        "prevClosePrice": 102.23,
                        "volume": 2953458,
                        "yearhHighInd": 0,
                        "yearhLowInd": 0,
                        "impliedVolatality": 0.2814,
                        "pctTenDayVol": 1.9848,
                        "peRatio": 15.697,
                        "yield": 0.9782,
                        "tradingStatus": 1,
                        "lastTime": "22:16:43.000",
                        "vendor": "RBDS"
                    },
                    "defaultVendor": "RBDS",
                    "delayed": false,
                    "vendorKeys": [
                        "RBDS",
                        "ARCA",
                        "NLS"
                    ]
                },
                {
                    "issueId": 284350,
                    "cnbcSymbol": "WDC",
                    "vendorSymbol": "WDC.O",
                    "symbolDesc": "Western Digital Corp",
                    "shares": null,
                    "cached": false,
                    "symbolData": {
                        "lastPrice": 70.85,
                        "change": 2.61,
                        "changePct": 3.8247,
                        "changeAfter": 0.29,
                        "changePre": 0.66,
                        "changePctAfter": 0.4093,
                        "changePctPre": 0.9672,
                        "prevClosePrice": 68.24,
                        "volume": 12491846,
                        "yearhHighInd": 1,
                        "yearhLowInd": 0,
                        "impliedVolatality": 0.379,
                        "pctTenDayVol": 1.8605,
                        "peRatio": 0.0,
                        "yield": 0.0,
                        "tradingStatus": 1,
                        "lastTime": "22:32:23.000",
                        "vendor": "RBDS"
                    },
                    "defaultVendor": "RBDS",
                    "delayed": false,
                    "vendorKeys": [
                        "RBDS",
                        "ARCA",
                        "NLS"
                    ]
                },
                {
                    "issueId": 217004,
                    "cnbcSymbol": "NRG",
                    "vendorSymbol": "NRG",
                    "symbolDesc": "NRG Energy Inc",
                    "shares": null,
                    "cached": false,
                    "symbolData": {
                        "lastPrice": 70.15,
                        "change": 2.46,
                        "changePct": 3.6342,
                        "changeAfter": 0.13,
                        "changePre": -0.19,
                        "changePctAfter": 0.1853,
                        "changePctPre": -0.2807,
                        "prevClosePrice": 67.69,
                        "volume": 3717580,
                        "yearhHighInd": 1,
                        "yearhLowInd": 0,
                        "impliedVolatality": 0.3095,
                        "pctTenDayVol": 0.7324,
                        "peRatio": 0.0,
                        "yield": 2.408,
                        "tradingStatus": 1,
                        "lastTime": "22:31:04.000",
                        "vendor": "RBDS"
                    },
                    "defaultVendor": "RBDS",
                    "delayed": false,
                    "vendorKeys": [
                        "RBDS",
                        "ARCA",
                        "NLS"
                    ]
                },
                {
                    "issueId": 74964069,
                    "cnbcSymbol": "ANET",
                    "vendorSymbol": "ANET.K",
                    "symbolDesc": "Arista Networks Inc",
                    "shares": null,
                    "cached": false,
                    "symbolData": {
                        "lastPrice": 299.75,
                        "change": 9.77,
                        "changePct": 3.3692,
                        "changeAfter": 0.25,
                        "changePre": 2.31,
                        "changePctAfter": 0.0834,
                        "changePctPre": 0.7966,
                        "prevClosePrice": 289.98,
                        "volume": 1588693,
                        "yearhHighInd": 0,
                        "yearhLowInd": 0,
                        "impliedVolatality": 0.4045,
                        "pctTenDayVol": 0.511,
                        "peRatio": 44.0786,
                        "yield": 0.0,
                        "tradingStatus": 1,
                        "lastTime": "22:30:30.000",
                        "vendor": "RBDS"
                    },
                    "defaultVendor": "RBDS",
                    "delayed": false,
                    "vendorKeys": [
                        "RBDS",
                        "ARCA",
                        "NLS"
                    ]
                },
                {
                    "issueId": 136432,
                    "cnbcSymbol": "GD",
                    "vendorSymbol": "GD",
                    "symbolDesc": "General Dynamics Corp",
                    "shares": null,
                    "cached": false,
                    "symbolData": {
                        "lastPrice": 291.55,
                        "change": 9.06,
                        "changePct": 3.2072,
                        "changeAfter": 0.45,
                        "changePre": 4.97,
                        "changePctAfter": 0.1543,
                        "changePctPre": 1.7594,
                        "prevClosePrice": 282.49,
                        "volume": 1742935,
                        "yearhHighInd": 1,
                        "yearhLowInd": 0,
                        "impliedVolatality": 0.1798,
                        "pctTenDayVol": 2.0583,
                        "peRatio": 23.5105,
                        "yield": 2.0107,
                        "tradingStatus": 1,
                        "lastTime": "22:30:00.000",
                        "vendor": "RBDS"
                    },
                    "defaultVendor": "RBDS",
                    "delayed": false,
                    "vendorKeys": [
                        "RBDS",
                        "ARCA",
                        "NLS"
                    ]
                },
                {
                    "issueId": 46492,
                    "cnbcSymbol": "APA",
                    "vendorSymbol": "APA.O",
                    "symbolDesc": "APA Corp (US)",
                    "shares": null,
                    "cached": false,
                    "symbolData": {
                        "lastPrice": 35.43,
                        "change": 1.05,
                        "changePct": 3.0541,
                        "changeAfter": 0.06,
                        "changePre": 0.16,
                        "changePctAfter": 0.1693,
                        "changePctPre": 0.4654,
                        "prevClosePrice": 34.38,
                        "volume": 8325477,
                        "yearhHighInd": 0,
                        "yearhLowInd": 0,
                        "impliedVolatality": 0.3048,
                        "pctTenDayVol": 0.7608,
                        "peRatio": 3.7221,
                        "yield": 2.9087,
                        "tradingStatus": 0,
                        "lastTime": "22:31:26.000",
                        "vendor": "RBDS"
                    },
                    "defaultVendor": "RBDS",
                    "delayed": false,
                    "vendorKeys": [
                        "RBDS",
                        "ARCA",
                        "NLS"
                    ]
                },
                {
                    "issueId": 140864,
                    "cnbcSymbol": "GOOGL",
                    "vendorSymbol": "GOOGL.O",
                    "symbolDesc": "Alphabet Class A",
                    "shares": null,
                    "cached": false,
                    "symbolData": {
                        "lastPrice": 155.49,
                        "change": 4.56,
                        "changePct": 3.0213,
                        "changeAfter": -0.08,
                        "changePre": -0.17,
                        "changePctAfter": -0.0514,
                        "changePctPre": -0.1126,
                        "prevClosePrice": 150.93,
                        "volume": 31695784,
                        "yearhHighInd": 1,
                        "yearhLowInd": 0,
                        "impliedVolatality": 0.3066,
                        "pctTenDayVol": 1.033,
                        "peRatio": 26.022,
                        "yield": 0.0,
                        "tradingStatus": 1,
                        "lastTime": "22:32:55.000",
                        "vendor": "RBDS"
                    },
                    "defaultVendor": "RBDS",
                    "delayed": false,
                    "vendorKeys": [
                        "RBDS",
                        "ARCA",
                        "NLS"
                    ]
                },
                {
                    "issueId": 194567,
                    "cnbcSymbol": "LVS",
                    "vendorSymbol": "LVS",
                    "symbolDesc": "Las Vegas Sands Corp",
                    "shares": null,
                    "cached": false,
                    "symbolData": {
                        "lastPrice": 53.18,
                        "change": 1.48,
                        "changePct": 2.8627,
                        "changeAfter": 0.0,
                        "changePre": 0.43,
                        "changePctAfter": 0.0,
                        "changePctPre": 0.8317,
                        "prevClosePrice": 51.7,
                        "volume": 4666763,
                        "yearhHighInd": 0,
                        "yearhLowInd": 0,
                        "impliedVolatality": 0.3342,
                        "pctTenDayVol": 1.3436,
                        "peRatio": 32.3919,
                        "yield": 1.5474,
                        "tradingStatus": 1,
                        "lastTime": "22:30:00.000",
                        "vendor": "RBDS"
                    },
                    "defaultVendor": "RBDS",
                    "delayed": false,
                    "vendorKeys": [
                        "RBDS",
                        "ARCA",
                        "NLS"
                    ]
                },
                {
                    "issueId": 72887506,
                    "cnbcSymbol": "GOOG",
                    "vendorSymbol": "GOOG.O",
                    "symbolDesc": "Alphabet Class C",
                    "shares": null,
                    "cached": false,
                    "symbolData": {
                        "lastPrice": 156.5,
                        "change": 4.24,
                        "changePct": 2.7847,
                        "changeAfter": -0.04,
                        "changePre": -0.34,
                        "changePctAfter": -0.0256,
                        "changePctPre": -0.2233,
                        "prevClosePrice": 152.26,
                        "volume": 24452220,
                        "yearhHighInd": 1,
                        "yearhLowInd": 0,
                        "impliedVolatality": 0.3048,
                        "pctTenDayVol": 1.0385,
                        "peRatio": 26.2408,
                        "yield": 0.0,
                        "tradingStatus": 1,
                        "lastTime": "22:32:27.000",
                        "vendor": "RBDS"
                    },
                    "defaultVendor": "RBDS",
                    "delayed": false,
                    "vendorKeys": [
                        "RBDS",
                        "ARCA",
                        "NLS"
                    ]
                },
                {
                    "issueId": 7084606,
                    "cnbcSymbol": "SMCI",
                    "vendorSymbol": "SMCI.O",
                    "symbolDesc": "Super Micro Computer Inc",
                    "shares": null,
                    "cached": false,
                    "symbolData": {
                        "lastPrice": 1037.15,
                        "change": 27.12,
                        "changePct": 2.6851,
                        "changeAfter": 0.99,
                        "changePre": -0.07,
                        "changePctAfter": 0.0955,
                        "changePctPre": -0.0069,
                        "prevClosePrice": 1010.03,
                        "volume": 5176012,
                        "yearhHighInd": 0,
                        "yearhLowInd": 0,
                        "impliedVolatality": 0.8735,
                        "pctTenDayVol": 0.6285,
                        "peRatio": 78.9423,
                        "yield": 0.0,
                        "tradingStatus": 1,
                        "lastTime": "22:32:30.000",
                        "vendor": "RBDS"
                    },
                    "defaultVendor": "RBDS",
                    "delayed": false,
                    "vendorKeys": [
                        "RBDS",
                        "ARCA",
                        "NLS"
                    ]
                }
            ]
        },
        {
            "rankOrder": "BOTTOM",
            "rankedSymbols": [
                {
                    "issueId": 283581,
                    "cnbcSymbol": "WBA",
                    "vendorSymbol": "WBA.O",
                    "symbolDesc": "Walgreens Boots Alliance Inc",
                    "shares": null,
                    "cached": false,
                    "symbolData": {
                        "lastPrice": 19.54,
                        "change": -2.15,
                        "changePct": -9.9124,
                        "changeAfter": 0.045,
                        "changePre": -0.09,
                        "changePctAfter": 0.2303,
                        "changePctPre": -0.4149,
                        "prevClosePrice": 21.69,
                        "volume": 36103334,
                        "yearhHighInd": 0,
                        "yearhLowInd": 1,
                        "impliedVolatality": 0.3351,
                        "pctTenDayVol": 2.9764,
                        "peRatio": 0.0,
                        "yield": 4.6104,
                        "tradingStatus": 1,
                        "lastTime": "22:32:39.000",
                        "vendor": "RBDS"
                    },
                    "defaultVendor": "RBDS",
                    "delayed": false,
                    "vendorKeys": [
                        "RBDS",
                        "ARCA",
                        "NLS"
                    ]
                },
                {
                    "issueId": 243137,
                    "cnbcSymbol": "RMD",
                    "vendorSymbol": "RMD",
                    "symbolDesc": "Resmed Inc",
                    "shares": null,
                    "cached": false,
                    "symbolData": {
                        "lastPrice": 189.32,
                        "change": -8.71,
                        "changePct": -4.3983,
                        "changeAfter": 3.07,
                        "changePre": -0.93,
                        "changePctAfter": 1.6216,
                        "changePctPre": -0.4696,
                        "prevClosePrice": 198.03,
                        "volume": 1532654,
                        "yearhHighInd": 0,
                        "yearhLowInd": 0,
                        "impliedVolatality": 0.3557,
                        "pctTenDayVol": 1.4058,
                        "peRatio": 32.8077,
                        "yield": 0.9696,
                        "tradingStatus": 1,
                        "lastTime": "22:32:59.000",
                        "vendor": "RBDS"
                    },
                    "defaultVendor": "RBDS",
                    "delayed": false,
                    "vendorKeys": [
                        "RBDS",
                        "ARCA",
                        "NLS"
                    ]
                },
                {
                    "issueId": 85511126,
                    "cnbcSymbol": "ETSY",
                    "vendorSymbol": "ETSY.O",
                    "symbolDesc": "ETSY Inc",
                    "shares": null,
                    "cached": false,
                    "symbolData": {
                        "lastPrice": 65.9,
                        "change": -2.82,
                        "changePct": -4.1036,
                        "changeAfter": 0.05,
                        "changePre": -0.6,
                        "changePctAfter": 0.0759,
                        "changePctPre": -0.8731,
                        "prevClosePrice": 68.72,
                        "volume": 2955002,
                        "yearhHighInd": 0,
                        "yearhLowInd": 0,
                        "impliedVolatality": 0.4215,
                        "pctTenDayVol": 0.8768,
                        "peRatio": 30.3196,
                        "yield": 0.0,
                        "tradingStatus": 1,
                        "lastTime": "22:28:39.000",
                        "vendor": "RBDS"
                    },
                    "defaultVendor": "RBDS",
                    "delayed": false,
                    "vendorKeys": [
                        "RBDS",
                        "ARCA",
                        "NLS"
                    ]
                },
                {
                    "issueId": 145043,
                    "cnbcSymbol": "HD",
                    "vendorSymbol": "HD",
                    "symbolDesc": "Home Depot Inc",
                    "shares": null,
                    "cached": false,
                    "symbolData": {
                        "lastPrice": 368.03,
                        "change": -15.57,
                        "changePct": -4.0589,
                        "changeAfter": -0.03,
                        "changePre": -2.29,
                        "changePctAfter": -0.0082,
                        "changePctPre": -0.597,
                        "prevClosePrice": 383.6,
                        "volume": 4330553,
                        "yearhHighInd": 0,
                        "yearhLowInd": 0,
                        "impliedVolatality": 0.1702,
                        "pctTenDayVol": 1.1364,
                        "peRatio": 25.3991,
                        "yield": 2.3462,
                        "tradingStatus": 1,
                        "lastTime": "22:31:49.000",
                        "vendor": "RBDS"
                    },
                    "defaultVendor": "RBDS",
                    "delayed": false,
                    "vendorKeys": [
                        "RBDS",
                        "ARCA",
                        "NLS"
                    ]
                },
                {
                    "issueId": 276301,
                    "cnbcSymbol": "UHS",
                    "vendorSymbol": "UHS",
                    "symbolDesc": "Universal Health Services Inc",
                    "shares": null,
                    "cached": false,
                    "symbolData": {
                        "lastPrice": 175.21,
                        "change": -7.25,
                        "changePct": -3.9735,
                        "changeAfter": -0.51,
                        "changePre": -2.12,
                        "changePctAfter": -0.2911,
                        "changePctPre": -1.1619,
                        "prevClosePrice": 182.46,
                        "volume": 1348003,
                        "yearhHighInd": 0,
                        "yearhLowInd": 0,
                        "impliedVolatality": 0.253,
                        "pctTenDayVol": 2.212,
                        "peRatio": 17.7998,
                        "yield": 0.4385,
                        "tradingStatus": 1,
                        "lastTime": "22:30:00.000",
                        "vendor": "RBDS"
                    },
                    "defaultVendor": "RBDS",
                    "delayed": false,
                    "vendorKeys": [
                        "RBDS",
                        "ARCA",
                        "NLS"
                    ]
                },
                {
                    "issueId": 75202,
                    "cnbcSymbol": "CHRW",
                    "vendorSymbol": "CHRW.O",
                    "symbolDesc": "CH Robinson Worldwide Inc",
                    "shares": null,
                    "cached": false,
                    "symbolData": {
                        "lastPrice": 73.34,
                        "change": -2.8,
                        "changePct": -3.6774,
                        "changeAfter": 0.0,
                        "changePre": -1.21,
                        "changePctAfter": 0.0,
                        "changePctPre": -1.5892,
                        "prevClosePrice": 76.14,
                        "volume": 1324700,
                        "yearhHighInd": 0,
                        "yearhLowInd": 0,
                        "impliedVolatality": 0.259,
                        "pctTenDayVol": 0.5545,
                        "peRatio": 28.0534,
                        "yield": 3.2046,
                        "tradingStatus": 1,
                        "lastTime": "22:26:30.000",
                        "vendor": "RBDS"
                    },
                    "defaultVendor": "RBDS",
                    "delayed": false,
                    "vendorKeys": [
                        "RBDS",
                        "ARCA",
                        "NLS"
                    ]
                },
                {
                    "issueId": 35875,
                    "cnbcSymbol": "HWM",
                    "vendorSymbol": "HWM",
                    "symbolDesc": "Howmet Aerospace Inc",
                    "shares": null,
                    "cached": false,
                    "symbolData": {
                        "lastPrice": 66.11,
                        "change": -2.32,
                        "changePct": -3.3903,
                        "changeAfter": -0.11,
                        "changePre": -0.32,
                        "changePctAfter": -0.1664,
                        "changePctPre": -0.4676,
                        "prevClosePrice": 68.43,
                        "volume": 3389132,
                        "yearhHighInd": 0,
                        "yearhLowInd": 0,
                        "impliedVolatality": 0.2282,
                        "pctTenDayVol": 0.9658,
                        "peRatio": 37.3642,
                        "yield": 0.2923,
                        "tradingStatus": 1,
                        "lastTime": "22:30:00.000",
                        "vendor": "RBDS"
                    },
                    "defaultVendor": "RBDS",
                    "delayed": false,
                    "vendorKeys": [
                        "RBDS",
                        "ARCA",
                        "NLS"
                    ]
                },
                {
                    "issueId": 165578,
                    "cnbcSymbol": "ILMN",
                    "vendorSymbol": "ILMN.O",
                    "symbolDesc": "Illumina Inc",
                    "shares": null,
                    "cached": false,
                    "symbolData": {
                        "lastPrice": 132.72,
                        "change": -4.6,
                        "changePct": -3.3498,
                        "changeAfter": 0.0,
                        "changePre": 1.47,
                        "changePctAfter": 0.0,
                        "changePctPre": 1.0705,
                        "prevClosePrice": 137.32,
                        "volume": 1264343,
                        "yearhHighInd": 0,
                        "yearhLowInd": 0,
                        "impliedVolatality": 0.469,
                        "pctTenDayVol": 0.7588,
                        "peRatio": 0.0,
                        "yield": 0.0,
                        "tradingStatus": 1,
                        "lastTime": "21:51:55.000",
                        "vendor": "RBDS"
                    },
                    "defaultVendor": "RBDS",
                    "delayed": false,
                    "vendorKeys": [
                        "RBDS",
                        "ARCA",
                        "NLS"
                    ]
                },
                {
                    "issueId": 105814,
                    "cnbcSymbol": "FDX",
                    "vendorSymbol": "FDX",
                    "symbolDesc": "FedEx Corp",
                    "shares": null,
                    "cached": false,
                    "symbolData": {
                        "lastPrice": 280.13,
                        "change": -9.61,
                        "changePct": -3.3168,
                        "changeAfter": 0.0,
                        "changePre": -5.08,
                        "changePctAfter": 0.0,
                        "changePctPre": -1.7533,
                        "prevClosePrice": 289.74,
                        "volume": 2783727,
                        "yearhHighInd": 0,
                        "yearhLowInd": 0,
                        "impliedVolatality": 0.1677,
                        "pctTenDayVol": 0.8632,
                        "peRatio": 16.6779,
                        "yield": 1.7395,
                        "tradingStatus": 1,
                        "lastTime": "22:31:56.000",
                        "vendor": "RBDS"
                    },
                    "defaultVendor": "RBDS",
                    "delayed": false,
                    "vendorKeys": [
                        "RBDS",
                        "ARCA",
                        "NLS"
                    ]
                },
                {
                    "issueId": 2634746,
                    "cnbcSymbol": "EXPE",
                    "vendorSymbol": "EXPE.O",
                    "symbolDesc": "Expedia Group Inc",
                    "shares": null,
                    "cached": false,
                    "symbolData": {
                        "lastPrice": 133.22,
                        "change": -4.53,
                        "changePct": -3.2886,
                        "changeAfter": 0.28,
                        "changePre": -0.07,
                        "changePctAfter": 0.2102,
                        "changePctPre": -0.0508,
                        "prevClosePrice": 137.75,
                        "volume": 3621630,
                        "yearhHighInd": 0,
                        "yearhLowInd": 0,
                        "impliedVolatality": 0.3159,
                        "pctTenDayVol": 1.8022,
                        "peRatio": 25.6223,
                        "yield": 0.0,
                        "tradingStatus": 1,
                        "lastTime": "22:24:50.000",
                        "vendor": "RBDS"
                    },
                    "defaultVendor": "RBDS",
                    "delayed": false,
                    "vendorKeys": [
                        "RBDS",
                        "ARCA",
                        "NLS"
                    ]
                },
                {
                    "issueId": 76758758,
                    "cnbcSymbol": "SYF",
                    "vendorSymbol": "SYF",
                    "symbolDesc": "Synchrony Financial",
                    "shares": null,
                    "cached": false,
                    "symbolData": {
                        "lastPrice": 41.75,
                        "change": -1.37,
                        "changePct": -3.1772,
                        "changeAfter": -0.5,
                        "changePre": -0.17,
                        "changePctAfter": -1.1976,
                        "changePctPre": -0.3942,
                        "prevClosePrice": 43.12,
                        "volume": 4081768,
                        "yearhHighInd": 0,
                        "yearhLowInd": 0,
                        "impliedVolatality": 0.3048,
                        "pctTenDayVol": 0.8906,
                        "peRatio": 8.3246,
                        "yield": 2.3191,
                        "tradingStatus": 1,
                        "lastTime": "22:30:00.000",
                        "vendor": "RBDS"
                    },
                    "defaultVendor": "RBDS",
                    "delayed": false,
                    "vendorKeys": [
                        "RBDS",
                        "ARCA",
                        "NLS"
                    ]
                },
                {
                    "issueId": 68160,
                    "cnbcSymbol": "BXP",
                    "vendorSymbol": "BXP",
                    "symbolDesc": "Boston Properties Inc",
                    "shares": null,
                    "cached": false,
                    "symbolData": {
                        "lastPrice": 63.29,
                        "change": -2.02,
                        "changePct": -3.0929,
                        "changeAfter": 0.21,
                        "changePre": -0.01,
                        "changePctAfter": 0.3318,
                        "changePctPre": -0.0153,
                        "prevClosePrice": 65.31,
                        "volume": 775063,
                        "yearhHighInd": 0,
                        "yearhLowInd": 0,
                        "impliedVolatality": 0.3319,
                        "pctTenDayVol": 0.5254,
                        "peRatio": 54.0266,
                        "yield": 6.0021,
                        "tradingStatus": 1,
                        "lastTime": "22:30:00.000",
                        "vendor": "RBDS"
                    },
                    "defaultVendor": "RBDS",
                    "delayed": false,
                    "vendorKeys": [
                        "RBDS",
                        "ARCA",
                        "NLS"
                    ]
                }
            ]
        }
    ]
}